-- Legacy migration script — superseded by create_tables.sql under /database
-- Tables are created directly in APP_DB_1967 via the SQL script in /database/create_tables.sql
-- This file is retained only as a placeholder to prevent Flyway from complaining
-- if Flyway auto-migration is ever enabled later.
--
-- Actual DDL → see: database/create_tables.sql
